apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: opa
  labels:
    app: opa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: opa
      name: opa
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa:0.15.1
        ports:
        - name: http
          containerPort: 8181
        args: ["run", "--ignore=.*", "--server", "--config-file", "/config/configuration_opa.yaml"]

        volumeMounts:
        - readOnly: true
          mountPath: /config
          name: config-opa

      volumes:
      - name: config-opa
        configMap:
          name: config-opa
